[/]
maximize=@as []
switch-applications=['<Control>Tab']
switch-applications-backward=['<Shift><Control>Tab']
switch-group=['<Control>grave']
switch-group-backward=['<Shift><Control>grave']
unmaximize=@as []
